# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-01 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='description',
            new_name='MyDescriptionList',
        ),
        migrations.RenameField(
            model_name='mydescriptionlist',
            old_name='description_list',
            new_name='description_field',
        ),
    ]
